### ISSUE TITLE
EPUB files are missing images

### ISSUE THREAD

**Issue by MaciekTalaska** [Michael-F-Bryan/mdbook-epub#19]
Thanks for your work.

I have generated an epub from the latest sources of the 'Rust Programming Language', but the generated EPUB is missing images.

Am I doing something wrong? Or is this feature missing at the moment?

**Comment by Michael-F-Bryan** [comment]
Hmm... I'm not sure what's wrong here. We have [a test](https://github.com/Michael-F-Bryan/mdbook-epub/blob/8923ad4cc630a60389cd4e6e07ecb31f4b441096/src/resources.rs#L109) which checks to make sure we can detect image assets in a document. Then later on [it uses](https://github.com/Michael-F-Bryan/mdbook-epub/blob/8923ad4cc630a60389cd4e6e07ecb31f4b441096/src/generator.rs#L133) the `resources::find()` method to find all assets so they can be embedded.

That said, I haven't done much/any development on this crate in quite a while, and didn't test it very thoroughly. So I wouldn't be surprised if there were logical bugs around embedding assets...

**Comment by MaciekTalaska** [comment]
Thanks for your reply.

What I was trying to do is to make EPUB from the sources of [The Rust Programming Language](https://github.com/rust-lang/book). 

My OS is Ubuntu derivative, with kernel 5.0.0-15

I am using Rust 1.34.0. Before trying to use `mdbook-epub` I have built and installed `mdbook` and then `mdbook-epub`.

My steps were as follows:
1. Cloned the git repo of the book
2. Edited the `book.toml` file as required for `mdbook-epub`. The file after the changes is as follows:
```toml
[book]
title = "The Rust Programming Language"
author = "Steve Klabnik and Carol Nichols, with Contributions from the Rust Community"

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]

[output.epub]
```
3. I have navigated to the folder where the TRPL has been cloned to, and I issued the command: `mdbook build`. It resulted in `book` directory being created and also an `epub` subdirectory containing the epub file.
The ferris images are missing (I thought initially this could be a problem with SVG files only, but other images are missing too - for example those used in Chapter 4).

Is there anything else I could try?
